apiVersion: v1
kind: Deployment
metadata:
  name: outofstock
  labels:
    name: outofstock
  namespace: outofstock
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: outofstock
    spec:
      containers:
      - name: selenium-hub
        image: selenium/standalone-chrome
        ports:
        - name: standalone-chrome
          containerPort: 4444
