
---
apiVersion: v1
kind: Service
metadata:
  name: outofstock-selenium-server
  labels:
    app: outofstock
spec:
  ports:
    - port: 4444
  selector:
    app: outofstock
    tier: selenium-server
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: outofstock
  labels:
    app: outofstock
spec:
  replicas: 1
  selector:
    matchLabels:
      app: outofstock
  template:
    metadata:
      labels:
        app: outofstock
    spec:
      containers:
      - name: seleniumchrome
        image: selenium/standalone-chrome
        ports:
        - containerPort: 4444
        volumeMounts:
        - mountPath: /dev/shm
          name: dev-shm
      volumes:
        - name: dev-shm
          emptyDir:
            medium: Memory
