apiVersion: apps/v1
kind: Deployment
metadata:
  name: outofstock
  labels:
    app: outofstock
spec:
  replicas: 1
  selector:
    matchLabels:
      app: outofstock
  template:
    metadata:
      labels:
        app: outofstock
    spec:
      containers:
      - name: seleniumchrome
        image: selenium/standalone-chrome
        ports:
        - containerPort: 4444
        volumeMounts:
        - mountPath: /dev/shm
          name: tmp-volume
      volumes:
        - name: dev-shm
          emptyDir:
            medium: Memory
